# Generated by Django 4.2.7 on 2024-01-28 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('file_name', models.CharField(max_length=255, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('file_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Biases',
            fields=[
                ('bias_id', models.AutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=255)),
                ('bias_text', models.CharField(max_length=255)),
                ('audit_response', models.BooleanField(blank=True, null=True)),
                ('reasoning', models.TextField()),
                ('file_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='impart.fileinfo')),
            ],
        ),
    ]
