# Generated by Django 4.2.7 on 2024-01-28 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('impart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biases',
            fields=[
                ('bias_id', models.AutoField(primary_key=True, serialize=False)),
                ('bias_text', models.CharField(max_length=255)),
                ('audit_response', models.BooleanField(blank=True, null=True)),
                ('reasoning', models.TextField()),
                ('file_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='impart.fileinfo')),
            ],
        ),
    ]
