# Generated by Django 4.2.7 on 2024-01-28 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impart', '0002_biases'),
    ]

    operations = [
        migrations.AddField(
            model_name='biases',
            name='model_name',
            field=models.CharField(default='Model', max_length=255),
            preserve_default=False,
        ),
    ]
